export default [{
  name: 'Transition',
  to: '/react-transition-group/transition'
}, {
  name: 'CssTransition',
  to: '/react-transition-group/csstransition'
}, {
  name: 'TransitionGroup',
  to: '/react-transition-group/transitiongroup'
}, {
  name: 'react-motion',
  to: '/react-transition-group/reactmotion'
}, {
  name: 'css-modules',
  to: '/react-transition-group/cssmodules'
}, {
  name: 'react-helmet',
  to: '/react-transition-group/react-helmet'
}, {
  name: 'decorator',
  to: '/react-transition-group/decorator'
}, {
  name: 'redux-thunk',
  to: '/redux/thunk'
}, {
  name: 'mobx',
  to: '/mobx'
}, {
  name: 'react-dnd',
  to: '/react-dnd'
}, {
  name: 'react-loadable',
  to: '/react-loadable'
}, {
  name: 'react-loadable-visibility',
  to: '/react-loadable-visibility'
}]